// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Qe1ba-ziAuEHrvbywxgfluEB4U4-_IU',
    appId: '1:555888098044:android:bb37a0afe87d004c04f579',
    messagingSenderId: '555888098044',
    projectId: 'fir-esp8266-8e47b',
    databaseURL: 'https://fir-esp8266-8e47b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp8266-8e47b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbW60QEY-wDzgEv67KNEPXSBKrTxRp374',
    appId: '1:555888098044:ios:1dcb204d65d8f98c04f579',
    messagingSenderId: '555888098044',
    projectId: 'fir-esp8266-8e47b',
    databaseURL: 'https://fir-esp8266-8e47b-default-rtdb.firebaseio.com',
    storageBucket: 'fir-esp8266-8e47b.appspot.com',
    iosBundleId: 'com.example.iotProject',
  );
}
